// <auto-generated />
using System;
using IDSmarters.AdminPortal.Data.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IDSmarters.AdminPortal.Migrations
{
    [DbContext(typeof(IDSmarterDbContext))]
    [Migration("20250415163409_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IDSmarters.AdminPortal.Models.AdminDashboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeanDashboardId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstructorDashboardId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentDashboardId")
                        .HasColumnType("int");

                    b.Property<int>("TotalDeans")
                        .HasColumnType("int");

                    b.Property<int>("TotalInstructors")
                        .HasColumnType("int");

                    b.Property<int>("TotalStudents")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeanDashboardId");

                    b.HasIndex("InstructorDashboardId");

                    b.HasIndex("StudentDashboardId");

                    b.ToTable("AdminDashboard");
                });

            modelBuilder.Entity("IDSmarters.AdminPortal.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("IDSmarters.AdminPortal.Models.DeanDashboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstructorDashboardId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentDashboardId")
                        .HasColumnType("int");

                    b.Property<int>("TotalStudents")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstructorDashboardId");

                    b.HasIndex("StudentDashboardId");

                    b.ToTable("DeanDashboard");
                });

            modelBuilder.Entity("IDSmarters.AdminPortal.Models.DepProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DepPrograms");
                });

            modelBuilder.Entity("IDSmarters.AdminPortal.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYear")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PreRegistrationId")
                        .HasColumnType("int");

                    b.Property<string>("Semester")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("PreRegistrationId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("IDSmarters.AdminPortal.Models.InstructorDashboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstructorDetailId")
                        .HasColumnType("int");

                    b.Property<int?>("InstructorDetailsId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentDashboardId")
                        .HasColumnType("int");

                    b.Property<int>("TotalStudents")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstructorDetailsId");

                    b.HasIndex("StudentDashboardId");

                    b.ToTable("InstructorDashboard");
                });

            modelBuilder.Entity("IDSmarters.AdminPortal.Models.InstructorsDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PreRegistrationId")
                        .HasColumnType("int");

                    b.Property<int>("ProgramId")
                        .HasColumnType("int");

                    b.Property<int?>("ProgramsId")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("Strand")
                        .HasColumnType("int");

                    b.Property<int?>("StrandsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PreRegistrationId");

                    b.HasIndex("ProgramsId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("StrandsId");

                    b.ToTable("InstructorDetails");
                });

            modelBuilder.Entity("IDSmarters.AdminPortal.Models.PreRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int?>("DepProgramId")
                        .HasColumnType("int");

                    b.Property<string>("Document1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Document2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Document3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Document4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastSchool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Municipality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purok")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Religion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("Sname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StrandId")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudNum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("DepProgramId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("StrandId");

                    b.ToTable("PreRegistration");
                });

            modelBuilder.Entity("IDSmarters.AdminPortal.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Day")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Room")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("IDSmarters.AdminPortal.Models.Strand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Strands");
                });

            modelBuilder.Entity("IDSmarters.AdminPortal.Models.StudentDashboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PreRegistrationId")
                        .HasColumnType("int");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PreRegistrationId");

                    b.ToTable("StudentDashboard");
                });

            modelBuilder.Entity("IDSmarters.AdminPortal.Models.StudentDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<int?>("PreRegistrationId")
                        .HasColumnType("int");

                    b.Property<int?>("ProgramId")
                        .HasColumnType("int");

                    b.Property<int?>("ProgramsId")
                        .HasColumnType("int");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int?>("StrandId")
                        .HasColumnType("int");

                    b.Property<int?>("StudentDashboardId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("PreRegistrationId");

                    b.HasIndex("ProgramsId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("StrandId");

                    b.HasIndex("StudentDashboardId");

                    b.ToTable("StudentDetails");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("IDSmarters.AdminPortal.Models.AdminDashboard", b =>
                {
                    b.HasOne("IDSmarters.AdminPortal.Models.DeanDashboard", "DeanDashboards")
                        .WithMany("AdminDashoards")
                        .HasForeignKey("DeanDashboardId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("IDSmarters.AdminPortal.Models.InstructorDashboard", "InstructorDashboards")
                        .WithMany("AdminDashoards")
                        .HasForeignKey("InstructorDashboardId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("IDSmarters.AdminPortal.Models.StudentDashboard", "StudentDashboards")
                        .WithMany("AdminDashoards")
                        .HasForeignKey("StudentDashboardId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("DeanDashboards");

                    b.Navigation("InstructorDashboards");

                    b.Navigation("StudentDashboards");
                });

            modelBuilder.Entity("IDSmarters.AdminPortal.Models.DeanDashboard", b =>
                {
                    b.HasOne("IDSmarters.AdminPortal.Models.InstructorDashboard", "InstructorDashboards")
                        .WithMany("DeanDashboards")
                        .HasForeignKey("InstructorDashboardId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("IDSmarters.AdminPortal.Models.StudentDashboard", "StudentDashboards")
                        .WithMany("DeanDashboards")
                        .HasForeignKey("StudentDashboardId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("InstructorDashboards");

                    b.Navigation("StudentDashboards");
                });

            modelBuilder.Entity("IDSmarters.AdminPortal.Models.Enrollment", b =>
                {
                    b.HasOne("IDSmarters.AdminPortal.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IDSmarters.AdminPortal.Models.PreRegistration", "PreRegistration")
                        .WithMany("Enrollments")
                        .HasForeignKey("PreRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("PreRegistration");
                });

            modelBuilder.Entity("IDSmarters.AdminPortal.Models.InstructorDashboard", b =>
                {
                    b.HasOne("IDSmarters.AdminPortal.Models.InstructorsDetail", "InstructorDetails")
                        .WithMany("InstructorDashboards")
                        .HasForeignKey("InstructorDetailsId");

                    b.HasOne("IDSmarters.AdminPortal.Models.StudentDashboard", "StudentDashboards")
                        .WithMany()
                        .HasForeignKey("StudentDashboardId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("InstructorDetails");

                    b.Navigation("StudentDashboards");
                });

            modelBuilder.Entity("IDSmarters.AdminPortal.Models.InstructorsDetail", b =>
                {
                    b.HasOne("IDSmarters.AdminPortal.Models.PreRegistration", "PreRegistrations")
                        .WithMany()
                        .HasForeignKey("PreRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IDSmarters.AdminPortal.Models.DepProgram", "Programs")
                        .WithMany()
                        .HasForeignKey("ProgramsId");

                    b.HasOne("IDSmarters.AdminPortal.Models.Schedule", "Schedules")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IDSmarters.AdminPortal.Models.Strand", "Strands")
                        .WithMany()
                        .HasForeignKey("StrandsId");

                    b.Navigation("PreRegistrations");

                    b.Navigation("Programs");

                    b.Navigation("Schedules");

                    b.Navigation("Strands");
                });

            modelBuilder.Entity("IDSmarters.AdminPortal.Models.PreRegistration", b =>
                {
                    b.HasOne("IDSmarters.AdminPortal.Models.Course", null)
                        .WithMany("PreRegistrations")
                        .HasForeignKey("CourseId");

                    b.HasOne("IDSmarters.AdminPortal.Models.DepProgram", null)
                        .WithMany("PreRegistrations")
                        .HasForeignKey("DepProgramId");

                    b.HasOne("IDSmarters.AdminPortal.Models.Schedule", null)
                        .WithMany("PreRegistrations")
                        .HasForeignKey("ScheduleId");

                    b.HasOne("IDSmarters.AdminPortal.Models.Strand", null)
                        .WithMany("PreRegistrations")
                        .HasForeignKey("StrandId");
                });

            modelBuilder.Entity("IDSmarters.AdminPortal.Models.StudentDashboard", b =>
                {
                    b.HasOne("IDSmarters.AdminPortal.Models.PreRegistration", "PreRegistrations")
                        .WithMany("StudentDashboards")
                        .HasForeignKey("PreRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreRegistrations");
                });

            modelBuilder.Entity("IDSmarters.AdminPortal.Models.StudentDetail", b =>
                {
                    b.HasOne("IDSmarters.AdminPortal.Models.Course", "Courses")
                        .WithMany()
                        .HasForeignKey("CourseId");

                    b.HasOne("IDSmarters.AdminPortal.Models.Enrollment", "Enrollments")
                        .WithMany()
                        .HasForeignKey("EnrollmentId");

                    b.HasOne("IDSmarters.AdminPortal.Models.PreRegistration", null)
                        .WithMany("Students")
                        .HasForeignKey("PreRegistrationId");

                    b.HasOne("IDSmarters.AdminPortal.Models.DepProgram", "Programs")
                        .WithMany()
                        .HasForeignKey("ProgramsId");

                    b.HasOne("IDSmarters.AdminPortal.Models.Schedule", "Schedules")
                        .WithMany()
                        .HasForeignKey("ScheduleId");

                    b.HasOne("IDSmarters.AdminPortal.Models.Strand", "Strands")
                        .WithMany()
                        .HasForeignKey("StrandId");

                    b.HasOne("IDSmarters.AdminPortal.Models.StudentDashboard", null)
                        .WithMany("Students")
                        .HasForeignKey("StudentDashboardId");

                    b.Navigation("Courses");

                    b.Navigation("Enrollments");

                    b.Navigation("Programs");

                    b.Navigation("Schedules");

                    b.Navigation("Strands");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IDSmarters.AdminPortal.Models.Course", b =>
                {
                    b.Navigation("PreRegistrations");
                });

            modelBuilder.Entity("IDSmarters.AdminPortal.Models.DeanDashboard", b =>
                {
                    b.Navigation("AdminDashoards");
                });

            modelBuilder.Entity("IDSmarters.AdminPortal.Models.DepProgram", b =>
                {
                    b.Navigation("PreRegistrations");
                });

            modelBuilder.Entity("IDSmarters.AdminPortal.Models.InstructorDashboard", b =>
                {
                    b.Navigation("AdminDashoards");

                    b.Navigation("DeanDashboards");
                });

            modelBuilder.Entity("IDSmarters.AdminPortal.Models.InstructorsDetail", b =>
                {
                    b.Navigation("InstructorDashboards");
                });

            modelBuilder.Entity("IDSmarters.AdminPortal.Models.PreRegistration", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("StudentDashboards");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("IDSmarters.AdminPortal.Models.Schedule", b =>
                {
                    b.Navigation("PreRegistrations");
                });

            modelBuilder.Entity("IDSmarters.AdminPortal.Models.Strand", b =>
                {
                    b.Navigation("PreRegistrations");
                });

            modelBuilder.Entity("IDSmarters.AdminPortal.Models.StudentDashboard", b =>
                {
                    b.Navigation("AdminDashoards");

                    b.Navigation("DeanDashboards");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
